version: '4'
services: 
  app:
    build: .
    volumes:
     - .:/django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
     - 8000:8000
    image: peterlillie/django-app:latest
    container_name: django_container
    depends_on:
      - db
  db:
    image: peterlillie/django-postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    image: peterlillie/django-nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/var/www/staticfiles
    depends_on: 
    - app
